# Generated by Django 3.2.8 on 2021-11-01 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211101_1703'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesforpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 3, 11, 673956, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 3, 11, 675591, tzinfo=utc), editable=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ('publication_date',),
            },
        ),
    ]
