# Generated by Django 3.2.8 on 2021-11-01 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 3, 11, 671036, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 3, 11, 670997, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='default_avatar/1.png', upload_to='user_avatars/'),
        ),
    ]
